# Due to rate limiting from digikey.com and gnu.org
accept = [429]

cache = true
exclude = [
  # Raspberry Pi's website returns 403 forbidden codes.
  '^https://www.raspberrypi.com',
]
exclude_path = [
  ".cache/",
  ".direnv/",
  ".flatpak/",
  ".flatpak-builder/",
  "build.*/",
  "repo/",
]
max_cache_age = "2w"
