name: Format C++ code
"on":
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/format/clang-format.yaml
      - flake.lock
      - '**/.clang-format'
      - '**.cpp'
      - '**.hpp'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Check C++ formatting
        run: nix develop --command nu --commands 'clang-format --Werror **/*.cpp **/*.hpp'
