name: Format CMake files
"on":
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/format/cmake-format.yaml
      - flake.lock
      - '**/.cmake-format.json'
      - '**.cmake'
      - '**/CMakeLists.txt'

jobs:
  cmake-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Check CMake formatting
        run: nix develop --command nu --commands 'cmake-format --check **/CMakeLists.txt **/*.cmake'
