name: Lint
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ["main"]

permissions:
  checks: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  cmake-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Format CMake files
        id: cmake-format
        uses: PuneetMatharu/cmake-format-lint-action@v1.0.4
        with:
          args: --check
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.18.1
        with:
          source: '.'
          extensions: 'hpp,cpp'
  just:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
        with:
          just-version: "1.35.0"
      - name: Format justfile
        run: just --fmt --unstable
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: just
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: karancode/yamllint-github-action@v2.1.1
