name: Lint
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: ["main"]

permissions:
  checks: write
  contents: read
  issues: write
  pull-requests: write

jobs:
  cmake-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Format CMake files
        id: cmake-format
        uses: PuneetMatharu/cmake-format-lint-action@v1.0.4
        with:
          args: --in-place
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: ruff
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          format-review: true
          tidy-review: true
  just:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
        with:
          just-version: "1.24.0"
      - name: Format justfile
        run: just --fmt --unstable
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: just
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: chartboost/ruff-action@v1
        with:
          args: format
      - uses: chartboost/ruff-action@v1
        with:
          args: check --fix
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: ruff
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: karancode/yamllint-github-action@v2.1.1
