name: auto-ruff-format
on: [pull_request]  # yamllint disable-line rule:truthy

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: chartboost/ruff-action@v1
        with:
          args: format
      - uses: chartboost/ruff-action@v1
        with:
          args: check --fix
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: CMake Robot
          author_email: robot@jwillikers.com
          message: ':art: Committing ruff changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
