name: "schedule"
"on":
  workflow_dispatch:
  schedule:
    - cron: "0 0 3 * *" # run on the 3rd of every month

jobs:
  coverage-main-branch:
    strategy:
      matrix:
        compiler: [clang]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")
      - name: ccache cache files
        uses: actions/cache@v4
        with:
          key: coverage-${{ matrix.compiler }}-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          path: .ccache
          # This avoids the size of the cache increasing after every run.
          restore-keys: |
              coverage-${{ matrix.compiler }}-ccache-
          save-always: true
      - name: Generate Coverage
        run: nix develop --command just workflow coverage-${{ matrix.compiler }}
      - uses: clearlyip/code-coverage-report-action@v4
        with:
          filename: build-coverage-${{ matrix.compiler }}/cobertura.xml
