name: yamllint
on: [pull_request]  # yamllint disable-line rule:truthy

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: karancode/yamllint-github-action@v2.1.1
